### ISSUE TITLE
regarding media

### ISSUE THREAD

**Issue by maelle** [DaveParr/dev.to.ol#1]
I saw your [post about looking for an alternative to imgur](https://dev.to/daveparr/recommend-an-image-hosting-service-for-my-dev-to-api-wrapper-55ko).

I was thinking of one solution for posts that are hosted on a public GitHub repository: the post could have a YAML field indicating the URL to a folder in a GitHub repo, and in the post you could add the "raw URL" to image paths.

* Example of a (Hugo) post folder https://github.com/ropensci/roweb2/tree/master/content/blog/2020-04-07-bookdown-learnings

* Path for preview-check.png = https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2020-04-07-bookdown-learnings/preview-check.png

My issue with things like imgur is that it encourages users to not really own their image.

On the other hand forcing people to use one folder per post and a GitHub repo makes things less easy to set up (but the "one folder per post" part makes it easier to migrate to Hugo or so later down the road :-) ).

For context I've been thinking about similar issues whilst trying to create a minimal prototype for posting to Wordpress. Thankfully Wordpress has an API for media, but I was thinking "just" using imgur would be easier for me.

**Comment by DaveParr** [comment]
All great stuff. Thanks @maelle . I'll likely do exactly this :)

**Comment by maelle** [comment]
Also, you might want to explore issues / post a feature request at https://github.com/thepracticaldev/dev.to/issues

**Comment by DaveParr** [comment]
I think this is now 'fixed' with the GitHub hosting approach in the[ v0.1 release](https://github.com/DaveParr/dev.to.ol/releases/tag/v0.1.0)
